Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/ros/humble/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 38, in <module>
  File "/opt/ros/humble/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 38, in <module>
    sys.exit(main())
    sys.exit(main())
  File "/opt/ros/humble/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 34, in main
  File "/opt/ros/humble/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 34, in main
    generate_c(args.generator_arguments_file)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_c/__init__.py", line 37, in generate_c
    generate_cpp(args.generator_arguments_file)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_cpp/__init__.py", line 39, in generate_cpp
    return generate_files(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_cmake/__init__.py", line 87, in generate_files
    return generate_files(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_cmake/__init__.py", line 74, in generate_files
    expand_template(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_cmake/__init__.py", line 149, in expand_template
    idl_file = parse_idl_file(locator)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_parser/parser.py", line 64, in parse_idl_file
gmake[2]: *** Eliminazione del file «rosidl_generator_cpp/px4_msgs/msg/action_request.hpp»
    interpreter.string(template_content, template_path, locals=data)
  File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
    content = parse_idl_string(string, png_file=png_file)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_parser/parser.py", line 72, in parse_idl_string
gmake[2]: *** Eliminazione del file «rosidl_generator_c/px4_msgs/msg/action_request.h»
    tree = get_ast_from_idl_string(idl_string)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_parser/parser.py", line 89, in get_ast_from_idl_string
    return _parser.parse(idl_string)
  File "/usr/lib/python3/dist-packages/lark/lark.py", line 619, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/usr/lib/python3/dist-packages/lark/parser_frontends.py", line 99, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/usr/lib/python3/dist-packages/lark/parsers/earley.py", line 266, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
  File "/usr/lib/python3/dist-packages/lark/parsers/xearley.py", line 144, in _parse
    self.predict_and_complete(i, to_scan, columns, transitives)
  File "/usr/lib/python3/dist-packages/lark/parsers/earley.py", line 154, in predict_and_complete
    elif new_item not in column:
  File "/usr/lib/python3/dist-packages/lark/parsers/earley_common.py", line 28, in __eq__
    def __eq__(self, other):
KeyboardInterrupt
gmake[2]: *** [CMakeFiles/px4_msgs__cpp.dir/build.make:1205: rosidl_generator_cpp/px4_msgs/msg/action_request.hpp] Interruzione
gmake[1]: *** [CMakeFiles/Makefile2:265: CMakeFiles/px4_msgs__cpp.dir/all] Interruzione
    self.safe(scanner, True, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1543, in run
    sequence = interpreter.evaluate(sequenceCode, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2570, in evaluate
    self.invoke('beforeEvaluate', 
  File "/usr/lib/python3/dist-packages/em.py", line 2633, in invoke
    def invoke(self, _name, **keywords):
KeyboardInterrupt
Exception ignored in: <function Interpreter.__del__ at 0x74974d540ee0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/em.py", line 2094, in __del__
  File "/usr/lib/python3/dist-packages/em.py", line 2157, in shutdown
  File "/usr/lib/python3/dist-packages/em.py", line 2647, in finalize
  File "/usr/lib/python3/dist-packages/em.py", line 2200, in push
AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
gmake[2]: *** [CMakeFiles/px4_msgs__rosidl_generator_c.dir/build.make:274: rosidl_generator_c/px4_msgs/msg/action_request.h] Interruzione
gmake[1]: *** [CMakeFiles/Makefile2:212: CMakeFiles/px4_msgs__rosidl_generator_c.dir/all] Interruzione
gmake: *** [Makefile:146: all] Interruzione
